apiVersion: v1
kind: ConfigMap
metadata:
  name: ai6-be-config
  namespace: default
data:
  SPRING_JPA_HIBERNATE_DDL_AUTO: "update"
  SPRING_JPA_SHOW_SQL: "true"
  SPRING_JPA_PROPERTIES_HIBERNATE_DIALECT: "org.hibernate.dialect.MySQL8Dialect"
  SPRING_JPA_PROPERTIES_HIBERNATE_FORMAT_SQL: "true"
  SPRING_APPLICATION_NAME: "checkscamv2"
  SERVER_PORT: "8080"
  SPRING_DATASOURCE_DRIVER_CLASS_NAME: "com.mysql.cj.jdbc.Driver"
  SPRING_SERVLET_MULTIPART_MAX_FILE_SIZE: "50MB"
  SPRING_SERVLET_MULTIPART_MAX_REQUEST_SIZE: "50MB"
  SPRING_SERVLET_MULTIPART_ENABLED: "true"
  APP_UPLOAD_DIR: "uploads"
  CHECKSCAM_JWT_ACCESS_TOKEN_VALIDITY_IN_SECONDS: "86400"
  CHECKSCAM_JWT_REFRESH_TOKEN_VALIDITY_IN_SECONDS: "8640000"
  GEMINI_API_URL: "https://generativelanguage.googleapis.com/v1beta/models/gemini-2.0-flash:generateContent"
  GEMINI_TIMEOUT: "30000"
  GEMINI_MAX_RETRIES: "3"
  GOOGLE_RECAPTCHA_VERIFY_URL: "https://www.google.com/recaptcha/api/siteverify"
  OPENROUTER_API_URL: "https://openrouter.ai/api/v1/chat/completions"
  OPENROUTER_MODEL: "google/gemini-2.0-flash-001"
  OPENROUTER_TIMEOUT: "30000"
  OPENROUTER_MAX_RETRIES: "3"
  OPENROUTER_TEMPERATURE: "0.7"
  OPENROUTER_MAX_TOKENS: "1200"
  GOOGLE_OAUTH2_CLIENT_ID: "1040843887455-1lkcsjnnsbdlkpu2ge90bi20b2ptqd7u.apps.googleusercontent.com"
  LOGGING_LEVEL_COM_EXAMPLE_CHECKSCAMV2: "INFO"
  LOGGING_LEVEL_ORG_SPRINGFRAMEWORK_WEB: "INFO"
  LOGGING_LEVEL_ORG_HIBERNATE: "ERROR"
  SPRING_CACHE_TYPE: "caffeine"
  SPRING_CACHE_CAFFEINE_SPEC: "maximumSize=500,expireAfterWrite=600s"
  SPRING_MAIN_ALLOW_BEAN_DEFINITION_OVERRIDING: "true"
  PLAYWRIGHT_TIMEOUT: "1000"
  PLAYWRIGHT_DEFAULT_PROTOCOL: "https://"
  PLAYWRIGHT_VIEWPORT_WIDTH: "720"
  PLAYWRIGHT_VIEWPORT_HEIGHT: "1080"
  SPRING_WEB_RESOURCES_STATIC_LOCATIONS: "classpath:/static/,file:cache/"
  SPRING_WEBSOCKET_CORS_ALLOWED_ORIGINS: "http://localhost:4200,http://localhost:3000,http://127.0.0.1:4200"