apiVersion: v1
kind: ConfigMap
metadata:
  name: ai6-be-config
  namespace: default
data:
  # Application Configuration
  SPRING_APPLICATION_NAME: "checkscamv2"
  SERVER_PORT: "8080"
  
  # Database Configuration (non-sensitive)
  DB_DRIVER: "com.mysql.cj.jdbc.Driver"
  
  # JPA Configuration
  SPRING_JPA_SHOW_SQL: "true"
  SPRING_JPA_HIBERNATE_DDL_AUTO: "update"
  SPRING_JPA_PROPERTIES_HIBERNATE_DIALECT: "org.hibernate.dialect.MySQL8Dialect"
  SPRING_JPA_PROPERTIES_HIBERNATE_FORMAT_SQL: "true"
  
  # JWT Configuration (non-sensitive)
  JWT_ACCESS_TOKEN_VALIDITY: "86400"
  JWT_REFRESH_TOKEN_VALIDITY: "8640000"
  
  # File Upload Configuration
  MAX_FILE_SIZE: "50MB"
  MAX_REQUEST_SIZE: "50MB"
  UPLOAD_DIR: "uploads"
  
  # Gemini API Configuration (non-sensitive)
  GEMINI_API_URL: "https://generativelanguage.googleapis.com/v1beta/models/gemini-2.0-flash:generateContent"
  GEMINI_TIMEOUT: "30000"
  GEMINI_MAX_RETRIES: "3"
  
  # Google reCAPTCHA Configuration (non-sensitive)
  GOOGLE_RECAPTCHA_VERIFY_URL: "https://www.google.com/recaptcha/api/siteverify"
  
  # OpenRouter API Configuration (non-sensitive)
  OPENROUTER_API_URL: "https://openrouter.ai/api/v1/chat/completions"
  OPENROUTER_MODEL: "google/gemini-2.0-flash-001"
  OPENROUTER_TIMEOUT: "30000"
  OPENROUTER_MAX_RETRIES: "3"
  OPENROUTER_TEMPERATURE: "0.7"
  OPENROUTER_MAX_TOKENS: "1200"
  
  # Google OAuth2 Configuration (non-sensitive)
  GOOGLE_OAUTH2_CLIENT_ID: "1040843887455-1lkcsjnnsbdlkpu2ge90bi20b2ptqd7u.apps.googleusercontent.com"
  
  # Logging Configuration
  LOGGING_LEVEL_COM_EXAMPLE_CHECKSCAMV2: "INFO"
  LOGGING_LEVEL_ORG_SPRINGFRAMEWORK_WEB: "INFO"
  LOGGING_LEVEL_ORG_HIBERNATE: "ERROR"
  
  # Cache Configuration
  SPRING_CACHE_TYPE: "caffeine"
  SPRING_CACHE_CAFFEINE_SPEC: "maximumSize=500,expireAfterWrite=600s"
  
  # Rate Limiting Configuration
  RESILIENCE4J_RATELIMITER_INSTANCES_OPENROUTER_LIMITFORPERIOD: "50"
  RESILIENCE4J_RATELIMITER_INSTANCES_OPENROUTER_LIMITREFRESHPERIOD: "1s"
  RESILIENCE4J_RATELIMITER_INSTANCES_OPENROUTER_TIMEOUTDURATION: "0s"
  
  # Spring Configuration
  SPRING_MAIN_ALLOW_BEAN_DEFINITION_OVERRIDING: "true"
  SPRING_WEB_RESOURCES_STATIC_LOCATIONS: "classpath:/static/,file:cache/"
  
  # Playwright Configuration
  PLAYWRIGHT_TIMEOUT: "1000"
  PLAYWRIGHT_DEFAULT_PROTOCOL: "https://"
  PLAYWRIGHT_VIEWPORT_WIDTH: "720"
  PLAYWRIGHT_VIEWPORT_HEIGHT: "1080"
  
  # External APIs Configuration (non-sensitive URLs)
  GOOGLE_SAFE_BROWSE_API_URL: "https://safeBrowse.googleapis.com/v4/threatMatches:find"
  GOOGLE_WEB_RISK_API_URL: "https://webrisk.googleapis.com/v1/uris:search"
  PHISHTANK_API_URL: "http://checkurl.phishtank.com/checkurl/"
  VIRUSTOTAL_API_URL: "https://www.virustotal.com/api/v3/urls"
  URLSCAN_API_URL: "https://urlscan.io/api/v1/scan/"
  
  # WebSocket Configuration
  WEBSOCKET_CORS_ALLOWED_ORIGINS: "http://localhost:4200,https://localhost:4200,http://localhost:3000,https://localhost:3000,http://127.0.0.1:4200,https://127.0.0.1:4200,https://ai6.vn,https://www.ai6.vn"
  SPRING_WEBSOCKET_CORS_ALLOW_CREDENTIALS: "true"
  SPRING_WEBSOCKET_SOCKJS_HEARTBEAT_TIME: "25000"
  SPRING_WEBSOCKET_SOCKJS_DISCONNECT_DELAY: "5000"
