apiVersion: apps/v1
kind: Deployment
metadata:
  name: ai6-be-deployment
  namespace: default
  labels:
    app: ai6-be
spec:
  replicas: 3
  selector:
    matchLabels:
      app: ai6-be
  template:
    metadata:
      labels:
        app: ai6-be
    spec:
      containers:
      - name: ai6-be
        image: ai6-be:latest
        ports:
        - containerPort: 8080
        env:
        # Sensitive environment variables from Secret
        - name: DB_URL
          valueFrom:
            secretKeyRef:
              name: ai6-be-secret
              key: DB_URL
        - name: DB_USERNAME
          valueFrom:
            secretKeyRef:
              name: ai6-be-secret
              key: DB_USERNAME
        - name: DB_PASSWORD
          valueFrom:
            secretKeyRef:
              name: ai6-be-secret
              key: DB_PASSWORD
        - name: JWT_SECRET
          valueFrom:
            secretKeyRef:
              name: ai6-be-secret
              key: JWT_SECRET
        - name: GEMINI_API_KEY
          valueFrom:
            secretKeyRef:
              name: ai6-be-secret
              key: GEMINI_API_KEY
        - name: OPENROUTER_API_KEY
          valueFrom:
            secretKeyRef:
              name: ai6-be-secret
              key: OPENROUTER_API_KEY
        - name: GOOGLE_RECAPTCHA_SECRET
          valueFrom:
            secretKeyRef:
              name: ai6-be-secret
              key: GOOGLE_RECAPTCHA_SECRET
        - name: GOOGLE_SAFE_BROWSE_API_KEY
          valueFrom:
            secretKeyRef:
              name: ai6-be-secret
              key: GOOGLE_SAFE_BROWSE_API_KEY
        - name: GOOGLE_WEB_RISK_API_KEY
          valueFrom:
            secretKeyRef:
              name: ai6-be-secret
              key: GOOGLE_WEB_RISK_API_KEY
        - name: VIRUSTOTAL_API_KEY
          valueFrom:
            secretKeyRef:
              name: ai6-be-secret
              key: VIRUSTOTAL_API_KEY
        - name: URLSCAN_API_KEY
          valueFrom:
            secretKeyRef:
              name: ai6-be-secret
              key: URLSCAN_API_KEY
        - name: PHISHTANK_API_KEY
          valueFrom:
            secretKeyRef:
              name: ai6-be-secret
              key: PHISHTANK_API_KEY
        # All non-sensitive config from ConfigMap
        envFrom:
        - configMapRef:
            name: ai6-be-config
        resources:
          limits:
            cpu: "1"
            memory: "1Gi"
          requests:
            cpu: "0.5"
            memory: "512Mi"
        livenessProbe:
          httpGet:
            path: /actuator/health
            port: 8080
          initialDelaySeconds: 30
          periodSeconds: 10
        readinessProbe:
          httpGet:
            path: /actuator/health
            port: 8080
          initialDelaySeconds: 15
          periodSeconds: 5
