apiVersion: apps/v1
kind: Deployment
metadata:
  name: ai6-be-deployment
  namespace: default
  labels:
    app: ai6-be
spec:
  replicas: 2
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 0
      maxSurge: 1
  selector:
    matchLabels:
      app: ai6-be
  template:
    metadata:
      labels:
        app: ai6-be
    spec:
      containers:
      - name: ai6-be
        image: ai6-be:latest
        imagePullPolicy: Always
        ports:
        - containerPort: 8080
          name: http
        env:
        # Sensitive environment variables from Secret
        - name: DB_URL
          valueFrom:
            secretKeyRef:
              name: ai6-be-secret
              key: DB_URL
        - name: DB_USERNAME
          valueFrom:
            secretKeyRef:
              name: ai6-be-secret
              key: DB_USERNAME
        - name: DB_PASSWORD
          valueFrom:
            secretKeyRef:
              name: ai6-be-secret
              key: DB_PASSWORD
        - name: JWT_SECRET
          valueFrom:
            secretKeyRef:
              name: ai6-be-secret
              key: JWT_SECRET
        - name: GEMINI_API_KEY
          valueFrom:
            secretKeyRef:
              name: ai6-be-secret
              key: GEMINI_API_KEY
        - name: OPENROUTER_API_KEY
          valueFrom:
            secretKeyRef:
              name: ai6-be-secret
              key: OPENROUTER_API_KEY
        - name: GOOGLE_RECAPTCHA_SECRET
          valueFrom:
            secretKeyRef:
              name: ai6-be-secret
              key: GOOGLE_RECAPTCHA_SECRET
        - name: GOOGLE_SAFE_BROWSE_API_KEY
          valueFrom:
            secretKeyRef:
              name: ai6-be-secret
              key: GOOGLE_SAFE_BROWSE_API_KEY
        - name: GOOGLE_WEB_RISK_API_KEY
          valueFrom:
            secretKeyRef:
              name: ai6-be-secret
              key: GOOGLE_WEB_RISK_API_KEY
        - name: VIRUSTOTAL_API_KEY
          valueFrom:
            secretKeyRef:
              name: ai6-be-secret
              key: VIRUSTOTAL_API_KEY
        - name: URLSCAN_API_KEY
          valueFrom:
            secretKeyRef:
              name: ai6-be-secret
              key: URLSCAN_API_KEY
        - name: PHISHTANK_API_KEY
          valueFrom:
            secretKeyRef:
              name: ai6-be-secret
              key: PHISHTANK_API_KEY
        # All non-sensitive config from ConfigMap
        envFrom:
        - configMapRef:
            name: ai6-be-config
        resources:
          limits:
            cpu: "1000m"
            memory: "1.5Gi"
          requests:
            cpu: "500m"
            memory: "768Mi"
        livenessProbe:
          httpGet:
            path: /actuator/health/liveness
            port: 8080
            scheme: HTTP
          initialDelaySeconds: 120
          periodSeconds: 30
          timeoutSeconds: 10
          failureThreshold: 3
          successThreshold: 1
        readinessProbe:
          httpGet:
            path: /actuator/health/readiness
            port: 8080
            scheme: HTTP
          initialDelaySeconds: 30
          periodSeconds: 10
          timeoutSeconds: 5
          failureThreshold: 3
          successThreshold: 1
        startupProbe:
          httpGet:
            path: /actuator/health
            port: 8080
            scheme: HTTP
          initialDelaySeconds: 10
          periodSeconds: 10
          timeoutSeconds: 5
          failureThreshold: 12
          successThreshold: 1
        volumeMounts:
        - name: uploads-volume
          mountPath: /app/uploads
        - name: cache-volume
          mountPath: /app/cache
      volumes:
      - name: uploads-volume
        emptyDir: {}
      - name: cache-volume
        emptyDir: {}
      restartPolicy: Always