apiVersion: v1
kind: Secret
metadata:
  name: ai6-secrets
  namespace: default
type: Opaque
data:
  # Database Credentials (base64 encoded)
  SPRING_DATASOURCE_USERNAME: YWk2X3VzZXI=
  # Original: techbyteDev
  SPRING_DATASOURCE_PASSWORD: dGVjaGJ5dGVEZXY=

  # JWT Secret (base64 encoded)
  # Original: OxGm3cuh+eGvHosY4JGGAOvCU6QzTQVyAw7crvtCilLqqWKV+YX/V0ucUfXWqPYCJXLcexH7/4BSnRH4qNVaBA==
  AI6_JWT_BASE64_SECRET: T3hHbTNjdWgrZUd2SG9zWTRKR0dBT3ZDVTZRelRRVnlBdzdDcnZ0Q2lsTHFxV0tWK1lYL1YwdWNVZlhXcVBZQ0pYTGNleEg3LzRCU25STEQ0SkdOYUJBPT0=

  # API Keys (base64 encoded)
  # Original: AIzaSyAPgGTi2nijZ7aJtpGtQqnoqeVQp4HwIwk
  GEMINI_API_KEY: QUl6YVN5QVBnR1RpMm5palp3YUp0cEd0UXFub3FlVlFwNEh3SXdr

  # Original: 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
  OPENROUTER_API_KEY: c2stb3ItdjEtOTlkOWEzNWYxZTEyNDU1NWYwZmRlNGU2MTdhZWVjOThjODA5NDBkOGQxZjI5Y2FiZmEyNDNjODdhZmU4NWYzOA==

  # Original: 6LfG6TArAAAAACIVaSfqfaSGjvbiJdsNa_zA2idc
  GOOGLE_RECAPTCHA_SECRET: NkxmRzZUQXJBQUFBQUNJVmFTZnFmYVNHanZiaUpkc05hX3pBMmlkYw==

  # Original: AIzaSyA0f5CNKcpfD6BB5o-IiDlgSYfR6Zuu1bg
  GOOGLE_SAFE_BROWSING_API_KEY: QUl6YVN5QTBmNUNOS2NwZkQ2QkI1by1JaURsZ1NZZlI2WnV1MWJn
  GOOGLE_WEB_RISK_API_KEY: QUl6YVN5QTBmNUNOS2NwZkQ2QkI1by1JaURsZ1NZZlI2WnV1MWJn

  # Original: your_phish_tank_api_key (placeholder)
  PHISHTANK_API_KEY: eW91cl9waGlzaF90YW5rX2FwaV9rZXk=

  # Original: 1439662f8a02006c444db833ea94c68c005fb860b958c9d29d10719d41d095d2
  VIRUSTOTAL_API_KEY: MTQzOTY2MmY4YTAyMDA2YzQ0NGRiODMzZWE5NGM2OGMwMDVmYjg2MGI5NThjOWQyOWQxMDcxOWQ0MWQwOTVkMg==

  # Original: 01978cbe-8f0c-767e-91b7-d1d4d1db6acc
  URLSCAN_API_KEY: MDE5NzhjYmUtOGYwYy03NjdlLTkxYjctZDFkNGQxZGI2YWNj

  # Google OAuth2 Credentials (placeholder - you need to set these)
  # Original: your_google_client_id
  GOOGLE_CLIENT_ID: eW91cl9nb29nbGVfY2xpZW50X2lk
  # Original: your_google_client_secret
  GOOGLE_CLIENT_SECRET: eW91cl9nb29nbGVfY2xpZW50X3NlY3JldA==

---
# MySQL Secret
apiVersion: v1
kind: Secret
metadata:
  name: mysql-secret
  namespace: default
type: Opaque
data:
  MYSQL_USER: YWk2X3VzZXI=
  # Original: techbyteDev
  MYSQL_PASSWORD: dGVjaGJ5dGVEZXY=
  # Updated: ai6_database (YWk2X2RhdGFiYXNl)
  MYSQL_DATABASE: YWk2X2RhdGFiYXNl
  # Original: strongrootpassword123
  MYSQL_ROOT_PASSWORD: c3Ryb25ncm9vdHBhc3N3b3JkMTIz