apiVersion: v1
kind: Service
metadata:
  name: ai6-be
  namespace: default
  labels:
    app: ai6-be
spec:
  selector:
    app: ai6-be
  ports:
  - name: http
    protocol: TCP
    port: 80
    targetPort: 8080
  type: ClusterIP