apiVersion: apps/v1
kind: Deployment
metadata:
  name: ai6-fe-deployment
  namespace: default
  labels:
    app: ai6-fe
spec:
  replicas: 2
  selector:
    matchLabels:
      app: ai6-fe
  template:
    metadata:
      labels:
        app: ai6-fe
    spec:
      containers:
      - name: ai6-fe
        image: checkscam-fe:latest
        ports:
        - containerPort: 4200
        envFrom:
        - configMapRef:
            name: ai6-fe-config
        resources:
          limits:
            cpu: "0.5"
            memory: "512Mi"
          requests:
            cpu: "0.2"
            memory: "256Mi"
        livenessProbe:
          httpGet:
            path: /
            port: 4200
          initialDelaySeconds: 15
          periodSeconds: 10
        readinessProbe:
          httpGet:
            path: /
            port: 4200
          initialDelaySeconds: 5
          periodSeconds: 5