apiVersion: v1
kind: Service
metadata:
  name: ai6-fe-service
  namespace: default
  labels:
    app: ai6-fe
    version: v1
spec:
  selector:
    app: ai6-fe
  ports:
  - protocol: TCP
    port: 80
    targetPort: 4200
    name: http
  type: ClusterIP